kind: pipeline
type: docker
name: reprobuild
trigger:
  branch:
  - master
  - drone
#node:
#  location: office

steps:
  - name: Install TBD & build packages
    image: quay.io/podman/stable
    privileged: true
    environment:
      TBD_CRI: podman
    commands:
    #- sed -e 's|^metalink=|#metalink=|g' -e 's|^#baseurl=http:\/\/download.example\/pub\/fedora\/linux|baseurl=https:\/\/mirrors.ustc.edu.cn\/fedora|g' -i /etc/yum.repos.d/fedora*.repo
    - dnf install -y git findutils
    - git clone https://github.com/reproducible-tidb/TBD.git ../TBD
    - find ./*.TBD -type f -exec ../TBD/TBD.sh {} \;
    - rm -rf results && mkdir results && mv ./*.json results
  - name: Upload results
    image: appleboy/drone-git-push
    environment:
      PLUGIN_SSH_KEY:
        from_secret: GITHUB_SSH_KEY
    settings:
      remote: git@github.com:reproducible-tidb/packaging.git
      remote_name: release
      branch: results-drone
      commit: true
      commit_message: Drone CI build
      author_name: Drone CI
      author_email: runner@drone.zhoal.pw
      force: true

